# Artificial Neural Networks

## Importing the libraries

In [43]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [44]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [47]:
dataset = pd.read_csv('../Data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [48]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

### Encoding categorical data

Label Encoding the "Gender" column

In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [50]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

### Splitting the dataset into the Training set and Test set

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

### Feature Scaling

In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [53]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [54]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

### Adding the second hidden layer

In [55]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

### Adding the output layer

In [56]:
ann.add(tf.keras.layers.Dense(1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [57]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [58]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5281 - accuracy: 0.7747
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4708 - accuracy: 0.7952
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4461 - accuracy: 0.7987
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4278 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4092 - accuracy: 0.8205
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3922 - accuracy: 0.8298
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3797 - accuracy: 0.8361
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3710 - accuracy: 0.8421
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3653 - accuracy: 0.8446
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3612 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3295 - accuracy: 0.8594
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3292 - accuracy: 0.8600
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3293 - accuracy: 0.8599
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3297 - accuracy: 0.8596
Epoch 84/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3292 - accuracy: 0.8600
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3287 - accuracy: 0.8612
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3290 - accuracy: 0.8608
Epoch 87/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3288 - accuracy: 0.8602
Epoch 88/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3284 - accuracy: 0.8608
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3285 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [62]:
homework = sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

In [65]:
ann.predict(homework) > 0.5

array([[False]])

### Predicting the Test set results

In [68]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1537   47]
 [ 231  185]]


0.861