# Kernel PCA

## Importing the libraries 

In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [30]:
dataset = pd.read_csv('../Data/Wine.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

## Future Scaling

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Applying Kernel PCA

In [33]:
from sklearn.decomposition import KernelPCA
k_pca = KernelPCA(n_components = 2, kernel = 'rbf')
X_train = k_pca.fit_transform(X_train)
X_test = k_pca.transform(X_test)

## Training the Logistic Regression model on the Training Set

In [34]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression()

## Making the Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, clf.predict(X_test)))
accuracy_score(y_test, clf.predict(X_test))

[[12  1  0]
 [ 0 14  1]
 [ 0  1  7]]


0.9166666666666666